// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "gae-goa-sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/y-ogura/gae-goa-sample/design
// --out=$(GOPATH)/src/github.com/y-ogura/gae-goa-sample
// --version=v1.2.0-dirty

package client

import (
	"net/http"
)

// Example (default view)
//
// Identifier: application/vnd.example+json; view=default
type Example struct {
	// message
	Message *string `form:"message,omitempty" json:"message,omitempty" xml:"message,omitempty"`
}

// DecodeExample decodes the Example instance encoded in resp body.
func (c *Client) DecodeExample(resp *http.Response) (*Example, error) {
	var decoded Example
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
