// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "gae-goa-sample": Application User Types
//
// Command:
// $ goagen
// --design=github.com/y-ogura/gae-goa-sample/design
// --out=$(GOPATH)/src/github.com/y-ogura/gae-goa-sample
// --version=v1.2.0-dirty

package client
