// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "gae-goa-sample": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/y-ogura/gae-goa-sample/design
// --out=$(GOPATH)/src/github.com/y-ogura/gae-goa-sample
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// HelloWorldHelloContext provides the hello HelloWorld action context.
type HelloWorldHelloContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewHelloWorldHelloContext parses the incoming request URL and body, performs validations and creates the
// context used by the hello controller HelloWorld action.
func NewHelloWorldHelloContext(ctx context.Context, r *http.Request, service *goa.Service) (*HelloWorldHelloContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := HelloWorldHelloContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *HelloWorldHelloContext) OK(r *Example) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.example+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *HelloWorldHelloContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}
