// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "gae-goa-sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/y-ogura/gae-goa-sample/design
// --out=$(GOPATH)/src/github.com/y-ogura/gae-goa-sample
// --version=v1.2.0-dirty

package app

// Example (default view)
//
// Identifier: application/vnd.example+json; view=default
type Example struct {
	// message
	Message *string `form:"message,omitempty" json:"message,omitempty" xml:"message,omitempty"`
}
